import { Outfit } from "next/font/google";
import "./globals.css";
import GameContextProvider from "@/contexts/GameContextProvider";

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} bg-darkNavy`}>
        <GameContextProvider>{children}</GameContextProvider>
      </body>
    </html>
  );
}
